# Changes that are being made ---------------------------------------------

##### I believe that RQ1 needs to be changed, I think this because the research says that hemoglobin and hemaocrit have been to be predictors for absolute VO2 max in individuals. This is shown when we run a linear regressions where only blood metrics are the only predictors, they showed significance. Once we added body comp metrics those significance disappear. This shows that practically it may not be best practice to rely on invasive metrics like blood when running GxT with body comp metrics being recorded to predict VO2 max test. 

##### I mispoke on what hct is: What hct is not is the concentration of hemoglobin in the blood. Hct is the concentration of red blood cells in the blood volume.

# Intro -------------------------------------------------------------------

## The Overarching Question

##### If the purpose of collecting blood during a GXT is to better explain an individual's absolute VO2max, does Hb/Hct provide meaningful information beyond body composition?

##### Maximal oxygen consumption (VO2max) is widely used to characterize maximal aerobic capacity and reflects the integrated ability of the cardiovascular, respiratory, and muscular systems to transport and utilize oxygen during maximal exercise (Bassett & Howley, 2000; Levine, 2008). Oxygen transport is a key component of this process, with hemoglobin determining the oxygen-carrying capacity of blood (Webb et al., 2023). In a meta-analysis of 384 studies, both hemoglobin mass and hemoglobin concentration were positively associated with absolute VO₂max, but hemoglobin mass accounted for more of the between-study variance than concentration or hematocrit (Webb et al., 2023). This pattern is physiologically plausible because hemoglobin mass is closely tied to blood volume and cardiac output, whereas concentration and hematocrit are influenced by plasma volume and blood viscosity, and their changes do not always track changes in VO2max (Schmidt & Prommer, 2010; Webb et al., 2023). However, absolute VO2max is not determined by oxygen transport alone. Lean mass is positively associated with absolute VO2max (Haraldsdottir et al., 2022; Maciejczyk et al., 2014), and it also scales closely with blood volume and hemoglobin mass (Oberholzer et al., 2023). Consequently, associations between hematological characteristics and absolute VO2max may partly reflect their shared relationship with body composition. Lean mass may be particularly relevant to absolute VO2max because it represents metabolically active tissue capable of utilizing oxygen during exercise (Haraldsdottir et al., 2022; Maciejczyk et al., 2014) and because it scales closely with blood volume and hemoglobin mass (Oberholzer et al., 2023). Sex is also a major source of variation, influencing hemoglobin concentration, hematocrit, body composition, and VO2max, although sex differences in blood volume and hemoglobin mass shrink considerably once expressed relative to lean mass (Oberholzer et al., 2023). From a practical standpoint, assessing hemoglobin and hematocrit requires blood collection, whereas body composition can be assessed non-invasive. Determining whether hematological characteristics remain associated with absolute VO2max after accounting for body composition and demographic characteristics may therefore clarify their independent contribution to maximal aerobic capacity. In addition, absolute VO2max is typically higher during treadmill than cycle ergometer testing, although the difference varies widely across studies and populations (Kaminsky et al., 2022; Shephard, 1984), which may alter these relationships. The purpose of this study was to examine the associations of hemoglobin and hematocrit with absolute VO2max and to determine whether these associations remained after accounting for body composition and demographic characteristics. A secondary objective was to examine whether these associations differed by exercise modality.